[package]
name = "bm1366"
version = "0.1.0"
edition = "2021"

[dependencies]
"bm13xx-asic" = { path = "../bm13xx-asic" }
"bm13xx-protocol" = { path = "../bm13xx-protocol" }

fugit = "0.3"
heapless = "0.8"
