[package]
name = "bm13xx-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
crc = "3.2"
derive_more = { version = "1.0.0-beta", default-features = false, features = ["from"] }
heapless = "0.8"

[dev-dependencies]
serialport = { version="4.4", default-features = false}

[[example]]
name = "reg_probe"
path = "examples/reg_probe.rs"

[[example]]
name = "core_reg_probe"
path = "examples/core_reg_probe.rs"

[[example]]
name = "version_rolling"
path = "examples/version_rolling.rs"

[[example]]
name = "chain_enum"
path = "examples/chain_enum.rs"