[package]
name = "bm13xx-asic"
version = "0.1.0"
edition = "2021"

[dependencies]
bm13xx-protocol = { path = "../bm13xx-protocol" }

defmt = { version = "0.3", optional = true }
derive_more = { version = "1.0.0-beta", default-features = false, features = ["from"] }
fugit = "0.3"
heapless = "0.8"

[features]
defmt = ["dep:defmt", "fugit/defmt", "heapless/defmt-03"]