[package]
name = "bm13xx-asic"
version = "0.1.0"
edition = "2021"

[dependencies]
bm13xx-protocol = { path = "../bm13xx-protocol" }

defmt = { workspace = true, optional = true }
derive_more = { workspace = true, features = ["from"] }
fugit = { workspace = true }
heapless = { workspace = true }

[features]
defmt-03 = ["dep:defmt", "fugit/defmt", "heapless/defmt-03"]